######################################################################
# Automatically generated by qmake (2.01a) lun. 25. août 16:58:00 2008
######################################################################

TEMPLATE = app
QT += network

TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += configuration.h Launcher.h
SOURCES += configuration.cpp Launcher.cpp main.cpp
