######################################################################
# Automatically generated by qmake (2.01a) ven. 14. nov. 20:40:32 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network
QT += webkit

# Input
HEADERS += configuration.h Launcher.h
SOURCES += configuration.cpp Launcher.cpp main.cpp
