# #####################################################################
# Automatically generated by qmake (2.01a) mar. ao�t 10 22:59:45 2010
# #####################################################################
TEMPLATE = app
TARGET = ../../LauncherHolyspirit
DEPENDPATH += .
INCLUDEPATH += .
QT += network \
    webkit

# Input
HEADERS += configuration.h \
    Launcher.h \
    optionsjeu.h \
    defines.h
SOURCES += configuration.cpp \
    Launcher.cpp \
    main.cpp \
    optionsjeu.cpp
RC_FILE = ressource.rc
TRANSLATIONS += Languages\hslauncher_en.ts \
    Languages/hslauncher_es.ts \
    Languages/hslauncher_fr.ts \
    Languages/hslauncher_ru.ts \
    Languages/hslauncher_uk.ts
