SET (GNU_SRCPATH $ENV{PROGRAMFILES}/GnuWin32 $ENV{GNUWINDIR})
FIND_PATH(GNUWIN_INCLUDE_DIR libintl.h
  PATHS ${GNU_SRCPATH}
  PATH_SUFFIXES include
)

FIND_LIBRARY(GNUWIN_LIBRARY
  NAMES libintl.lib
  PATHS ${GNU_SRCPATH}
  PATH_SUFFIXES lib libs
)

MARK_AS_ADVANCED(
    GNUWIN_INCLUDE_DIR
    GNUWIN_LIBRARY
)
